name = "Pack 2"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1bc69e75f8a430cc42a4d713c3c72c3100057c18086f63b0ce38ba2dd9ac688"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
