name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89cab458b9286a1b4d10977c2c5ec485cc1544bb52a6846a279ae405f5cdcf10"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
