name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46fa1b8709059b0ac3c7ccc6c7bafeb51042ddae4e260368e9de584de3d4b468"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
