name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dc34bb4b8b17ac956b3b50e17dfb5396dcdd1ea6a57395cfc2b8e495f18ce01"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
