name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "380d2db9985508f3d80a415c0a65b6ee90fb3abdb8de87f516ea7fa719a8815f"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
