name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56c614210bcc4f39c1b60bdfee8fcfa3090039119e0067f9e203a90f6084ab4a"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
