name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d039a7e393b51340a42aa2c05fe9d73ceec7c174063b376d78eb4bcbce1dff2"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
