name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0097b34d460ce78517c05729205f1018b5df68f20eddeb0fb53b2684f3d95cc"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
