name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c498209ea4115bc07ca10ba1df44dfe7b51b3e7ca6becfda68b51d5b742b6cf8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
