name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04c5aa28a41395ae9ecfd71ee22eda566c34c163401506e8b9fb277905e917e6"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
