name = "Pack 2"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "475725e8fd41802fedc2dc2be7b6d150919ef04add2c616e4177ba1f84a0c527"

[versions]
fabric = "0.14.25"
minecraft = "1.20.1"
