name = "Create Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "802834b90f67dab51b33b10edc12b7e1e11ea4105205be77d9934ec883a32fee"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
