name = "Create Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07d1852366efcd77c215d14a49b517bf817431becb3c0b375db1e8c67a3c8061"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
