name = "Create Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b00b2817b83e00d36f9b54d706af022c2804e808a86bfc10a88b4f8de8652a9c"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
